const status=document.querySelector('#status');
const login=document.querySelector('#login');
const editor=document.querySelector('#editor');
let setup=false;
async function api(url,method='GET',body){const response=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Er ging iets mis.');return data;}
async function refresh(){const session=await api('/api/session');setup=session.setup;login.hidden=session.authenticated;editor.hidden=!session.authenticated;document.querySelector('#login-title').textContent=setup?'Kies een beheerderswachtwoord':'Inloggen';login.querySelector('button').textContent=setup?'Wachtwoord instellen':'Inloggen';login.elements.password.minLength=setup?12:1;login.elements.password.autocomplete=setup?'new-password':'current-password';if(session.authenticated){const saved=await api('/api/weekly');document.querySelector('#fields').replaceChildren();for(const id of ['89','60']){const original=PRODUCTS.find(p=>p.id===id);const item=saved[id]||{...original,cents:original.variants[0].cents};const group=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=id==='89'?'Broodje van de week':'Salade van de week';group.append(legend);for(const [key,label] of [['name','Naam'],['description','Omschrijving en ingrediënten'],['price','Prijs in euro']]){const wrapper=document.createElement('label');wrapper.textContent=label;const input=document.createElement(key==='description'?'textarea':'input');input.name=`${id}-${key}`;if(key==='price'){input.type='number';input.min='0';input.max='1000';input.step='0.01';input.value=item.cents===null?'':(item.cents/100).toFixed(2);const help=document.createElement('small');help.textContent='Laat leeg voor prijs op aanvraag.';wrapper.append(help);}else{input.required=true;input.maxLength=key==='name'?100:600;input.value=item[key];if(key==='description')input.rows=4;}wrapper.append(input);group.append(wrapper);}document.querySelector('#fields').append(group);}}}
login.addEventListener('submit',async event=>{event.preventDefault();const button=login.querySelector('button');button.disabled=true;try{await api(setup?'/api/setup':'/api/login','POST',{password:login.elements.password.value});login.reset();status.textContent='Je bent ingelogd.';await refresh();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
editor.addEventListener('submit',async event=>{event.preventDefault();document.querySelector('#save').disabled=true;try{const data={};for(const id of ['89','60']){const price=editor.elements[`${id}-price`].value;data[id]={name:editor.elements[`${id}-name`].value.trim(),description:editor.elements[`${id}-description`].value.trim(),cents:price===''?null:Math.round(Number(price)*100)};}await api('/api/weekly','PUT',data);status.textContent='Opgeslagen. De weeksuggesties zijn bijgewerkt.';}catch(error){status.textContent=error.message;}finally{document.querySelector('#save').disabled=false;}});
document.querySelector('#logout').addEventListener('click',async()=>{try{await api('/api/logout','POST',{});await refresh();status.textContent='Je bent uitgelogd.';}catch(error){status.textContent=error.message;}});
refresh().catch(()=>status.textContent='Het beheerpaneel heeft de Piccolo-server nodig. Open de website via het lokale serveradres.');
