const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8080/admin');await p.locator('#login:visible').waitFor();await p.locator('[name=password]').fill('Test-only-password-123');await p.locator('#login button').click();await p.locator('#editor:visible').waitFor();
 await p.locator('[name="89-name"]').fill('Broodje testweek');await p.locator('[name="89-description"]').fill('Kaas en verse groenten');await p.locator('[name="89-price"]').fill('7.25');await p.locator('[name="60-name"]').fill('Salade testweek');await p.locator('[name="60-price"]').fill('8.50');await p.locator('#save').click();await p.getByText('Opgeslagen. De weeksuggesties zijn bijgewerkt.').waitFor();
 const visitor=await b.newContext({reducedMotion:'reduce'});const v=await visitor.newPage();v.on('pageerror',e=>errors.push(e.message));await v.goto('http://127.0.0.1:8080');await v.locator('.weekly-card').first().waitFor();assert.match(await v.locator('#weekly-cards').innerText(),/Broodje testweek/);
 assert.equal((await visitor.request.put('http://127.0.0.1:8080/api/weekly',{headers:{Origin:'http://127.0.0.1:8080'},data:{}})).status(),401);
 assert.equal((await visitor.request.get('http://127.0.0.1:8080/.piccolo-data/admin.json')).status(),404);
 await v.locator('[data-filter=croques]').click();assert.equal(await v.locator('.menu-item:not(.is-hidden)').count(),4);
 await v.locator('[data-filter=burgers]').click();assert.equal(await v.locator('.menu-item:not(.is-hidden)').filter({hasText:'Bicky'}).count(),5);
 await v.locator('[data-filter=warm]').click();await v.locator('[data-product-id="09"] button').click();assert.equal(await v.locator('#sandwich-extras input[type=checkbox]:visible').count(),1);assert.equal(await v.locator('#sandwich-notes').isVisible(),false);assert.equal(await v.locator('#sandwich-sauce').isVisible(),false);await v.locator('#spaghetti-extra input').check();assert.match(await v.locator('#sandwich-price').innerText(),/11,50/);await v.locator('#sandwich-next').click();await v.locator('#sandwich-call').click();
 await v.locator('[data-product-id="104"] button').click();assert.equal(await v.locator('#sandwich-bread option').count(),5);await v.locator('#sandwich-bread').selectOption({label:'Volkoren sandwino krokant'});await v.locator('[value="Extra ei"]').check();assert.match(await v.locator('#sandwich-price').innerText(),/8,50/);assert.equal(await v.locator('#spaghetti-extra').isVisible(),false);await v.locator('#sandwich-next').click();await v.locator('#sandwich-call').click();
 await v.locator('[data-filter=broodjes]').click();await v.locator('[data-product-id="01"] button').click();await v.locator('[name=size][value="Klein broodje"]').check();await v.locator('#sandwich-next').click();assert(await v.locator('#sandwich-bread').isVisible());await v.keyboard.press('Escape');
 await v.locator('#cart-open').click();assert.match(await v.locator('#cart-total').innerText(),/20,00/);await v.locator('#customer-name').fill('Test');await v.evaluate(()=>window.open=url=>{window.testUrl=url;return null});await v.locator('#cart-send').click();const message=new URL(await v.evaluate(()=>window.testUrl)).searchParams.get('text');assert.match(message,/Extra potje gemalen kaas/);assert.match(message,/Volkoren sandwino krokant/);await v.keyboard.press('Escape');
 for(const width of [390,1280]){await v.setViewportSize({width,height:900});await v.locator('.weekly-section').scrollIntoViewIfNeeded();await v.screenshot({path:`/private/tmp/piccolo-weekly-${width}.png`});assert(await v.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 // Restore defaults through the same authenticated panel.
 await p.locator('[name="89-name"]').fill('Broodje van de week');await p.locator('[name="89-description"]').fill('Elke week een ander broodje aan een voordelige prijs. Vraag naar het aanbod van deze week.');await p.locator('[name="89-price"]').fill('');await p.locator('[name="60-name"]').fill('Salade van de week');await p.locator('[name="60-price"]').fill('');await p.locator('#save').click();await p.getByText('Opgeslagen. De weeksuggesties zijn bijgewerkt.').waitFor();await p.locator('#logout').click();await p.locator('#login:visible').waitFor();assert.deepEqual(errors,[]);await b.close();console.log('PASS: admin saves across sessions, access control, grouping, cheese, bread, prices and WhatsApp.');
})().catch(e=>{console.error(e);process.exit(1)});
